In [454]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [455]:
data_train = pd.read_csv("/Users/jiyi/Desktop/534/project2/train.csv")
data_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [456]:
data_train=data_train.drop(['Name', 'Ticket','PassengerId','Cabin'], axis=1)
data_train

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [457]:
data_train=data_train.dropna(axis=0)
data_train

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
885         0       3  female  39.0      0      5  29.1250        Q
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[712 rows x 8 columns]

In [458]:
data_train = pd.get_dummies(data_train, columns = ['Sex'], drop_first=True)
data_train= pd.get_dummies(data_train, columns = ['Embarked'], drop_first=True)
data_train.head(10)

Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  \
0          0       3  22.0      1      0   7.2500         1           0   
1          1       1  38.0      1      0  71.2833         0           0   
2          1       3  26.0      0      0   7.9250         0           0   
3          1       1  35.0      1      0  53.1000         0           0   
4          0       3  35.0      0      0   8.0500         1           0   
6          0       1  54.0      0      0  51.8625         1           0   
7          0       3   2.0      3      1  21.0750         1           0   
8          1       3  27.0      0      2  11.1333         0           0   
9          1       2  14.0      1      0  30.0708         0           0   
10         1       3   4.0      1      1  16.7000         0           0   

    Embarked_S  
0            1  
1            0  
2            1  
3            1  
4            1  
6            1  
7            1  
8            1  
9            0  
10           1

In [459]:
X_train = data_train[['Pclass','Age','SibSp','Parch','Fare','Sex_male','Embarked_Q','Embarked_S']]
y_train = data_train[['Survived']]
print(X_train) 
print(y_train)

     Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  Embarked_S
0         3  22.0      1      0   7.2500         1           0           1
1         1  38.0      1      0  71.2833         0           0           0
2         3  26.0      0      0   7.9250         0           0           1
3         1  35.0      1      0  53.1000         0           0           1
4         3  35.0      0      0   8.0500         1           0           1
..      ...   ...    ...    ...      ...       ...         ...         ...
885       3  39.0      0      5  29.1250         0           1           0
886       2  27.0      0      0  13.0000         1           0           1
887       1  19.0      0      0  30.0000         0           0           1
889       1  26.0      0      0  30.0000         1           0           0
890       3  32.0      0      0   7.7500         1           1           0

[712 rows x 8 columns]
     Survived
0           0
1           1
2           1
3           1
4     

In [460]:
from sklearn.model_selection import train_test_split
X_train_train, X_train_test, y_train_train, y_train_test = train_test_split(X_train,y_train, test_size = 0.2,random_state=0)

In [461]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler() 
X_train_scale=scaler.fit_transform(X_train_train[['Pclass','Fare','Age','SibSp','Parch']]) 
X_test_scale=scaler.transform(X_train_test[['Pclass','Fare','Age','SibSp','Parch']])

In [462]:
X_train_train['Pclass']=X_train_scale[:,0]
X_train_train['Fare']=X_train_scale[:,1]
X_train_train['Age']=X_train_scale[:,2]
X_train_train['SibSp']=X_train_scale[:,3]
X_train_train['Parch']=X_train_scale[:,4]

In [463]:
X_train_train

Pclass       Age     SibSp     Parch      Fare  Sex_male  Embarked_Q  \
867 -1.492803  0.117556 -0.539048 -0.503861  0.261289         1           0   
332 -1.492803  0.607589 -0.539048  0.624867  2.102763         1           0   
20  -0.303160  0.397575 -0.539048 -0.503861 -0.176799         1           0   
606  0.886482  0.047551 -0.539048 -0.503861 -0.500577         1           0   
379  0.886482 -0.722500 -0.539048 -0.503861 -0.502738         1           0   
..        ...       ...       ...       ...       ...       ...         ...   
885  0.886482  0.677593 -0.539048  5.139780 -0.120911         0           1   
239 -0.303160  0.257565 -0.539048 -0.503861 -0.422259         1           0   
791 -0.303160 -0.932514 -0.539048 -0.503861 -0.176799         1           0   
705 -0.303160  0.677593 -0.539048 -0.503861 -0.176799         1           0   
858  0.886482 -0.372476 -0.539048  2.882324 -0.297368         0           0   

     Embarked_S  
867           1  
332           1  
20            1  
606           1  
379           1  
..          ...  
885           0  
239           1  
791           1  
705           1  
858           0  

[569 rows x 8 columns]

In [464]:
X_train_test['Pclass']=X_test_scale[:,0]
X_train_test['Fare']=X_test_scale[:,1]
X_train_test['Age']=X_test_scale[:,2]
X_train_test['SibSp']=X_test_scale[:,3]
X_train_test['Parch']=X_test_scale[:,4]

In [465]:
X_train_test

Pclass       Age     SibSp     Parch      Fare  Sex_male  Embarked_Q  \
423  0.886482 -0.092458  0.514967  0.624867 -0.384255         0           0   
178 -0.303160  0.047551 -0.539048 -0.503861 -0.409293         1           0   
305 -1.492803 -1.988184  0.514967  1.753596  2.068559         1           0   
292 -0.303160  0.467579 -0.539048 -0.503861 -0.411528         1           0   
592  0.886482  1.237630 -0.539048 -0.503861 -0.512127         1           0   
..        ...       ...       ...       ...       ...       ...         ...   
850  0.886482 -1.772569  3.677011  1.753596 -0.082460         1           0   
703  0.886482 -0.302472 -0.539048 -0.503861 -0.503333         1           1   
124 -1.492803  1.727663 -0.539048  0.624867  0.740436         1           0   
471  0.886482  0.607589 -0.539048 -0.503861 -0.486865         1           0   
615 -0.303160 -0.372476  0.514967  1.753596  0.520684         0           0   

     Embarked_S  
423           1  
178           1  
305           1  
292           0  
592           1  
..          ...  
850           1  
703           0  
124           1  
471           1  
615           1  

[143 rows x 8 columns]

kernel SVM

In [466]:
from sklearn.svm import SVC
SVM_rbf = SVC(kernel="rbf",random_state=0) 
SVM_rbf.fit(X_train_train, y_train_train)

/Users/jiyi/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(random_state=0)

In [467]:
pred_SVM_rbf=SVM_rbf.predict(X_train_test)

In [468]:
y_train_test_SVM_rbf=y_train_test
y_train_test_SVM_rbf['Predict Data'] = pred_SVM_rbf.tolist() 
y_train_test_SVM_rbf.head(10)

Survived  Predict Data
423         0             0
178         0             0
305         1             1
292         0             0
592         0             0
595         0             0
472         1             1
54          0             0
456         0             0
111         0             1

In [469]:
from sklearn.metrics import confusion_matrix, accuracy_score 
cm_SVM_rbf=confusion_matrix(y_train_test_SVM_rbf['Survived'].values,pred_SVM_rbf)
cm_SVM_rbf

array([[73,  9],
       [18, 43]])

In [470]:
as_SVM_rbf=accuracy_score(y_train_test_SVM_rbf['Survived'].values,pred_SVM_rbf)
as_SVM_rbf

0.8111888111888111

In [471]:
SVM_poly = SVC(kernel="poly",random_state=0) 
SVM_poly.fit(X_train_train, y_train_train)

/Users/jiyi/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='poly', random_state=0)

In [472]:
pred_SVM_poly=SVM_poly.predict(X_train_test)

In [473]:
y_train_test_SVM_poly=y_train_test
y_train_test_SVM_poly['Predict Data'] = pred_SVM_poly.tolist() 
y_train_test_SVM_poly.head(10)

Survived  Predict Data
423         0             0
178         0             0
305         1             1
292         0             0
592         0             0
595         0             0
472         1             1
54          0             0
456         0             0
111         0             1

In [474]:
cm_SVM_poly=confusion_matrix(y_train_test_SVM_poly['Survived'].values,pred_SVM_poly)
cm_SVM_poly

array([[70, 12],
       [18, 43]])

In [475]:
as_SVM_poly=accuracy_score(y_train_test_SVM_poly['Survived'].values,pred_SVM_poly)
as_SVM_poly

0.7902097902097902

LR

In [476]:
from sklearn.linear_model import LogisticRegression 
Logistic = LogisticRegression(random_state=0) 
Logistic.fit(X_train_train, y_train_train)

/Users/jiyi/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [477]:
pred_Logistic=Logistic.predict(X_train_test)

In [478]:
y_train_test_Logistic=y_train_test
y_train_test_Logistic['Predict Data'] = pred_Logistic.tolist() 
y_train_test_Logistic.head(10)

Survived  Predict Data
423         0             0
178         0             0
305         1             1
292         0             0
592         0             0
595         0             0
472         1             1
54          0             0
456         0             0
111         0             1

In [479]:
cm_Logistic=confusion_matrix(y_train_test_Logistic['Survived'].values,pred_Logistic)
cm_Logistic

array([[74,  8],
       [18, 43]])

In [480]:
as_Logistic=accuracy_score(y_train_test_Logistic['Survived'].values,pred_Logistic)
as_Logistic

0.8181818181818182

KNN

In [481]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=5,metric="minkowski") 
KNN.fit(X_train_train, y_train_train)

/Users/jiyi/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [482]:
pred_KNN=KNN.predict(X_train_test)

/Users/jiyi/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [483]:
y_train_test_KNN=y_train_test
y_train_test_KNN['Predict Data'] = pred_KNN.tolist() 
y_train_test_KNN.head(10)

Survived  Predict Data
423         0             0
178         0             0
305         1             1
292         0             0
592         0             0
595         0             0
472         1             1
54          0             0
456         0             0
111         0             1

In [484]:
cm_KNN=confusion_matrix(y_train_test_KNN['Survived'].values,pred_KNN)
cm_KNN

array([[68, 14],
       [22, 39]])

In [485]:
as_KNN=accuracy_score(y_train_test_KNN['Survived'].values,pred_KNN)
as_KNN

0.7482517482517482

DT

In [486]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(criterion = 'entropy', random_state = 0) 
DT.fit(X_train_train, y_train_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [487]:
pred_DT=DT.predict(X_train_test)

In [488]:
y_train_test_DT=y_train_test
y_train_test_DT['Predict Data'] = pred_DT.tolist() 
y_train_test_DT.head(10)

Survived  Predict Data
423         0             1
178         0             0
305         1             0
292         0             0
592         0             0
595         0             0
472         1             1
54          0             0
456         0             0
111         0             1

In [489]:
cm_DT=confusion_matrix(y_train_test_DT['Survived'].values,pred_DT)
cm_DT

array([[60, 22],
       [10, 51]])

In [490]:
as_DT=accuracy_score(y_train_test_DT['Survived'].values,pred_DT)
as_DT

0.7762237762237763

RF

In [491]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=10, criterion = 'entropy', random_state=0) 
RF.fit(X_train_train, y_train_train)

/var/folders/51/q7zp7nmn2t9_b0xrm327f2780000gn/T/ipykernel_72237/4214827259.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RF.fit(X_train_train, y_train_train)


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [492]:
pred_RF=RF.predict(X_train_test)

In [493]:
y_train_test_RF=y_train_test
y_train_test_RF['Predict Data'] = pred_RF.tolist() 
y_train_test_RF.head(10)

Survived  Predict Data
423         0             1
178         0             1
305         1             1
292         0             0
592         0             0
595         0             0
472         1             1
54          0             0
456         0             0
111         0             1

In [494]:
cm_RF=confusion_matrix(y_train_test_RF['Survived'].values,pred_RF)
cm_RF

array([[66, 16],
       [14, 47]])

In [495]:
as_RF=accuracy_score(y_train_test_RF['Survived'].values,pred_RF)
as_RF

0.7902097902097902

Naive Bayes

In [496]:
from sklearn.naive_bayes import GaussianNB
bayes = GaussianNB()
bayes.fit(X_train_train, y_train_train)

/Users/jiyi/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [497]:
pred_bayes=bayes.predict(X_train_test)

In [498]:
y_train_test_bayes=y_train_test
y_train_test_bayes['Predict Data'] = pred_bayes.tolist() 
y_train_test_bayes.head(10)

Survived  Predict Data
423         0             1
178         0             0
305         1             1
292         0             0
592         0             0
595         0             0
472         1             1
54          0             1
456         0             0
111         0             1

In [499]:
cm_bayes=confusion_matrix(y_train_test_bayes['Survived'].values,pred_bayes)
cm_bayes

array([[66, 16],
       [20, 41]])

In [500]:
as_bayes=accuracy_score(y_train_test_bayes['Survived'].values,pred_bayes)
as_bayes

0.7482517482517482

In [501]:
print("SVM rbf accuracy score:",as_SVM_rbf)
print("SVM poly accuracy score:",as_SVM_poly)
print("Logistic accuracy score:",as_Logistic)
print("KNN accuracy score:",as_KNN)
print("DT accuracy score:",as_DT)
print("RF accuracy score:",as_RF)
print("Bayes accuracy score:",as_bayes)

SVM rbf accuracy score: 0.8111888111888111
SVM poly accuracy score: 0.7902097902097902
Logistic accuracy score: 0.8181818181818182
KNN accuracy score: 0.7482517482517482
DT accuracy score: 0.7762237762237763
RF accuracy score: 0.7902097902097902
Bayes accuracy score: 0.7482517482517482


In [502]:
print("SVM rbf confusion matrix:",cm_SVM_rbf)
print("SVM poly confusion matrix:",cm_SVM_poly)
print("Logistic confusion matrix:",cm_Logistic)
print("KNN confusion matrix:",cm_KNN)
print("DT confusion matrix:",cm_DT)
print("RF confusion matrix:",cm_RF)
print("Bayes confusion matrix:",cm_bayes)

SVM rbf confusion matrix: [[73  9]
 [18 43]]
SVM poly confusion matrix: [[70 12]
 [18 43]]
Logistic confusion matrix: [[74  8]
 [18 43]]
KNN confusion matrix: [[68 14]
 [22 39]]
DT confusion matrix: [[60 22]
 [10 51]]
RF confusion matrix: [[66 16]
 [14 47]]
Bayes confusion matrix: [[66 16]
 [20 41]]


In [503]:
data_test = pd.read_csv("/Users/jiyi/Desktop/534/project2/test.csv")
data_test.head(10)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
5          897       3                    Svensson, Mr. Johan Cervin    male   
6          898       3                          Connolly, Miss. Kate  female   
7          899       2                  Caldwell, Mr. Albert Francis    male   
8          900       3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female   
9          901       3                       Davies, Mr. John Samuel    male   

    Age  SibSp  Parch     Ticket     Fare Cabin Embarked  
0  34.5      0      0     330911   7.8292   NaN        Q  
1  47.0      1      0     363272   7.0000   NaN        S  
2  62.0      0      0     240276   9.6875   NaN        Q  
3  27.0      0      0     315154   8.6625   NaN        S  
4  22.0      1      1    3101298  12.2875   NaN        S  
5  14.0      0      0       7538   9.2250   NaN        S  
6  30.0      0      0     330972   7.6292   NaN        Q  
7  26.0      1      1     248738  29.0000   NaN        S  
8  18.0      0      0       2657   7.2292   NaN        C  
9  21.0      2      0  A/4 48871  24.1500   NaN        S

In [504]:
data_test=data_test.drop(['Name', 'Ticket','PassengerId','Cabin'], axis=1)

In [505]:
data_test=data_test.dropna()

In [506]:
data_test = pd.get_dummies(data_test, columns = ['Sex'], drop_first=True)
data_test= pd.get_dummies(data_test, columns = ['Embarked'], drop_first=True)
data_test.head(10)

Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  Embarked_S
0       3  34.5      0      0   7.8292         1           1           0
1       3  47.0      1      0   7.0000         0           0           1
2       2  62.0      0      0   9.6875         1           1           0
3       3  27.0      0      0   8.6625         1           0           1
4       3  22.0      1      1  12.2875         0           0           1
5       3  14.0      0      0   9.2250         1           0           1
6       3  30.0      0      0   7.6292         0           1           0
7       2  26.0      1      1  29.0000         1           0           1
8       3  18.0      0      0   7.2292         0           0           0
9       3  21.0      2      0  24.1500         1           0           1

In [507]:
X_test = data_test[['Pclass','Age','SibSp','Parch','Fare','Sex_male','Embarked_Q','Embarked_S']]
print(X_test) 

     Pclass   Age  SibSp  Parch      Fare  Sex_male  Embarked_Q  Embarked_S
0         3  34.5      0      0    7.8292         1           1           0
1         3  47.0      1      0    7.0000         0           0           1
2         2  62.0      0      0    9.6875         1           1           0
3         3  27.0      0      0    8.6625         1           0           1
4         3  22.0      1      1   12.2875         0           0           1
..      ...   ...    ...    ...       ...       ...         ...         ...
409       3   3.0      1      1   13.7750         0           0           1
411       1  37.0      1      0   90.0000         0           1           0
412       3  28.0      0      0    7.7750         0           0           1
414       1  39.0      0      0  108.9000         0           0           0
415       3  38.5      0      0    7.2500         1           0           1

[331 rows x 8 columns]


In [508]:
X_test_test=scaler.transform(X_test[['Pclass','Fare','Age','SibSp','Parch']])

In [509]:
X_test['Pclass']=X_test_test[:,0]
X_test['Fare']=X_test_test[:,1]
X_test['Age']=X_test_test[:,2]
X_test['SibSp']=X_test_test[:,3]
X_test['Parch']=X_test_test[:,4]
X_test.head(10)

Pclass       Age     SibSp     Parch      Fare  Sex_male  Embarked_Q  \
0  0.886482  0.362572 -0.539048 -0.503861 -0.501768         1           1   
1  0.886482  1.237630  0.514967 -0.503861 -0.516598         0           0   
2 -0.303160  2.287700 -0.539048 -0.503861 -0.468534         1           1   
3  0.886482 -0.162462 -0.539048 -0.503861 -0.486865         1           0   
4  0.886482 -0.512486  0.514967  0.624867 -0.422035         0           0   
5  0.886482 -1.072523 -0.539048 -0.503861 -0.476806         1           0   
6  0.886482  0.047551 -0.539048 -0.503861 -0.505345         0           1   
7 -0.303160 -0.232467  0.514967  0.624867 -0.123146         1           0   
8  0.886482 -0.792504 -0.539048 -0.503861 -0.512499         0           0   
9  0.886482 -0.582490  1.568981 -0.503861 -0.209884         1           0   

   Embarked_S  
0           0  
1           1  
2           0  
3           1  
4           1  
5           1  
6           0  
7           1  
8           0  
9           1

In [510]:
X_test

Pclass       Age     SibSp     Parch      Fare  Sex_male  Embarked_Q  \
0    0.886482  0.362572 -0.539048 -0.503861 -0.501768         1           1   
1    0.886482  1.237630  0.514967 -0.503861 -0.516598         0           0   
2   -0.303160  2.287700 -0.539048 -0.503861 -0.468534         1           1   
3    0.886482 -0.162462 -0.539048 -0.503861 -0.486865         1           0   
4    0.886482 -0.512486  0.514967  0.624867 -0.422035         0           0   
..        ...       ...       ...       ...       ...       ...         ...   
409  0.886482 -1.842574  0.514967  0.624867 -0.395433         0           0   
411 -1.492803  0.537584  0.514967 -0.503861  0.967788         0           1   
412  0.886482 -0.092458 -0.539048 -0.503861 -0.502738         0           0   
414 -1.492803  0.677593 -0.539048 -0.503861  1.305799         0           0   
415  0.886482  0.642591 -0.539048 -0.503861 -0.512127         1           0   

     Embarked_S  
0             0  
1             1  
2             0  
3             1  
4             1  
..          ...  
409           1  
411           0  
412           1  
414           0  
415           1  

[331 rows x 8 columns]

In [511]:
pred=Logistic.predict(X_test)

In [513]:
prediction=pd.DataFrame(pred)
prediction.columns=['Logistic Regressio']
prediction

Logistic Regressio
0                     0
1                     0
2                     0
3                     0
4                     1
..                  ...
326                   1
327                   1
328                   1
329                   1
330                   0

[331 rows x 1 columns]